package com.engagepoint.university.exam.util;

import com.engagepoint.university.exam.entity.Task;

import java.util.Random;

public class TaskGenerator {
    static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    static Random rnd = new Random();
    private static int id=0;

    public static Task genTask(){
        Task autogeneratedTask = new Task();
        autogeneratedTask.setName("Task" + id++);
        autogeneratedTask.setDescription(randomString(20));
        return autogeneratedTask;
    }

    private static String randomString(int len){
        StringBuilder sb = new StringBuilder( len );
        for( int i = 0; i < len; i++ ){
            sb.append( AB.charAt( rnd.nextInt(AB.length()) ) );
        }
        return sb.toString();
    }

}
